### ISSUE TITLE
inject() cannot be used in fields reliably

### ISSUE THREAD

**Issue by ademenev** [1CRM/oceanfront#77]
`inject()` cannot be used in fields reliably, the same is true for other functions that can be called from component's `setup()` function

the problem is that when creating new field types, we do not actually create new components, but just define a data structure  that is used by the generic field component. That way, fields do not have their own setup function, and cannot use inject.

We currently do use inject() in fields' init() functions, and that seems to work. But that works only when field's `type` and `format` props do not change.  OfField's `setup()` watches `type` and `format` and when any of those is changed, `init()` is called. The watch() uses `immediate` flag, so the first call happens immediately, in the context of `setup()`. But if later one of those props changes, `init()` is called again, now out of that context.

**Comment by andrewwhitehead** [comment]
I do have some plans for fixing this, that is why the field type initializer is renamed from `setup` to `init`, at least for now.

`OfField` will probably change to delegate the rendering to a child component (`OfInput` or `OfFieldInner` maybe?), and cause that component to be replaced instead of patched when relevant parameters have been updated using the `key` property. I would also like to investigate using template slots to implement custom renderings of field types, for example rendering a single column fields in a method consistent with an iOS or Android options panel.
